### ISSUE TITLE
build instructions

### ISSUE THREAD

**Issue by romanman** [codenvy/ide#439]
Hey Guys, 

Thanks for great tools. I am afraid your build instruction 
document is outdated, there is such path in the project:

 codenvy-packaging-standalone-tomcat/target/tomcat-ide

Can I get some help how to build it from source ?

@vparfonov @azatsarynnyy 

Thank in advance
Roman

**Comment by eivantsov** [comment]
Indeed, this is an outdated instruction on how to build SaaS version of Codenvy. I'll report it to the engineering team.

Probably, what you should be looking for is how to build Che https://github.com/codenvy/assembly-che or bare SDK - https://github.com/codenvy/sdk

**Comment by romanman** [comment]
Just notice that you've answered here 
thanks I will try this way.
